"""changing available_seats to 3 by default

Revision ID: 19a24ed5f4fe
Revises: 1d844d9920a0
Create Date: 2022-03-08 12:23:36.626135

"""
from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '19a24ed5f4fe'
down_revision = '1d844d9920a0'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('cab', 'available_seats',
               existing_type=mysql.INTEGER,
               server_default='3')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
