"""changing available_seats to 4 by default

Revision ID: 1d844d9920a0
Revises: eb2579cb9b14
Create Date: 2022-03-08 12:04:23.394226

"""
from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '1d844d9920a0'
down_revision = 'eb2579cb9b14'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('cab', 'available_seats',
               existing_type=mysql.INTEGER,
               server_default='4')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
