"""add available_seats column to cab table

Revision ID: 93649fd945e9
Revises: d311de753624
Create Date: 2022-03-08 09:57:55.825762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93649fd945e9'
down_revision = 'd311de753624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab', sa.Column('available_seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab', 'available_seats')
    # ### end Alembic commands ###
