"""add data in cab_type and devloper_type tables

Revision ID: d311de753624
Revises: 69d333559748
Create Date: 2022-03-04 16:41:27.372979

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd311de753624'
down_revision = '69d333559748'
branch_labels = None
depends_on = None


def upgrade():
   op.execute("INSERT INTO developer_type(type) VALUES('frontend')")
   op.execute("INSERT INTO developer_type(type) VALUES('backend')")

   op.execute("INSERT INTO cab_type(type) VALUES('f')")
   op.execute("INSERT INTO cab_type(type) VALUES('b')")
   op.execute("INSERT INTO cab_type(type) VALUES('fb')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
